#!/usr/bin/env node

/**
 * Umrah Dua Guide Build Script
 *
 * This script combines:
 * - HTML template (src/templates/index.html)
 * - JSON data files (src/data/*.json)
 * - Embedded JavaScript for rendering
 *
 * Output: Single self-contained index.html file
 */

const fs = require('fs');
const path = require('path');

// Load data files
const duas = require('./src/data/duas.json');
const themes = require('./src/data/themes.json');
const rounds = require('./src/data/rounds.json');

// Read the template
const templatePath = path.join(__dirname, 'src', 'templates', 'index.html');
let template = fs.readFileSync(templatePath, 'utf8');

// Generate embedded data JavaScript
const embeddedData = `
        // ===== GENERATED DATA (from JSON files) =====
        // Do not edit this section - it's auto-generated by build.js

        const DUA_LIBRARY = ${JSON.stringify(duas, null, 2)};
        const THEMES = ${JSON.stringify(themes, null, 2)};
        const ROUNDS = ${JSON.stringify(rounds, null, 2)};

        // ===== END GENERATED DATA =====
`;

// Replace placeholder in template
template = template.replace('/*DATA_PLACEHOLDER*/', embeddedData);

// Write output
const outputPath = path.join(__dirname, 'index.html');
fs.writeFileSync(outputPath, template, 'utf8');

console.log('✅ Build successful!');
console.log(`   Generated: ${outputPath}`);
console.log(`   Size: ${(template.length / 1024).toFixed(2)} KB`);
console.log(`   Duas: ${Object.keys(duas).length}`);
console.log(`   Themes: ${Object.keys(themes).length}`);
