#!/usr/bin/env node

/**
 * Umrah Dua Guide Build Script
 *
 * - Validates JSON data against schemas
 * - Embeds data into the HTML template
 * - Outputs a single self-contained index.html
 */

const fs = require('fs');
const path = require('path');
const Ajv = require('ajv');

const projectRoot = __dirname;
const dataDir = path.join(projectRoot, 'src', 'data');
const schemaDir = path.join(dataDir, 'schemas');
const templatePath = path.join(projectRoot, 'src', 'templates', 'index.html');
const outputPath = path.join(projectRoot, 'index.html');

const ajv = new Ajv({ allErrors: true, strict: false });

function loadJson(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  return JSON.parse(raw);
}

function loadSchema(name) {
  const schemaPath = path.join(schemaDir, `${name}.schema.json`);
  return loadJson(schemaPath);
}

function validateJson(data, schema, label) {
  const validate = ajv.compile(schema);
  const valid = validate(data);
  if (!valid) {
    const messages = validate.errors
      .map(err => `${err.instancePath || '/'} ${err.message}`)
      .join('\n');
    throw new Error(`Validation failed for ${label}:\n${messages}`);
  }
}

function main() {
  // Load schemas
  const schemas = {
    duas: loadSchema('duas'),
    themes: loadSchema('themes'),
    rounds: loadSchema('rounds'),
  };

  // Load data files
  const data = {
    duas: loadJson(path.join(dataDir, 'duas.json')),
    themes: loadJson(path.join(dataDir, 'themes.json')),
    rounds: loadJson(path.join(dataDir, 'rounds.json')),
  };

  // Validate data
  validateJson(data.duas, schemas.duas, 'duas.json');
  validateJson(data.themes, schemas.themes, 'themes.json');
  validateJson(data.rounds, schemas.rounds, 'rounds.json');

  // Preprocess info-type duas to build HTML with bullet lists (so runtime stays simple)
  const escapeHtml = (s = '') =>
    s
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');

  const renderInfoHtml = (text = '') => {
    const blocks = text.split('\n\n');
    const renderBlock = (block) => {
      const lines = block.split('\n').filter(l => l.trim().length > 0);
      const bullets = lines.filter(l => l.trim().startsWith('•'));
      const lead = lines.filter(l => !l.trim().startsWith('•')).join(' ');

      if (bullets.length === 0) {
        return `<div class="translation text-accent mb-10">${escapeHtml(block)}</div>`;
      }

      const leadHtml = lead
        ? `<div class="translation text-accent mb-10">${escapeHtml(lead)}</div>`
        : '';

      const bulletHtml = `<ul class="dua-list">${bullets
        .map(b => `<li>${escapeHtml(b.replace(/^\s*•\s*/, ''))}</li>`)
        .join('')}</ul>`;

      return `${leadHtml}${bulletHtml}`;
    };

    return blocks.map(renderBlock).join('');
  };

  const duasWithDerived = Object.fromEntries(
    Object.entries(data.duas).map(([id, dua]) => {
      const copy = { ...dua };
      if (copy.type === 'info' && typeof copy.text === 'string') {
        copy.infoHtml = renderInfoHtml(copy.text);
      }
      return [id, copy];
    })
  );

  // Read template
  let template = fs.readFileSync(templatePath, 'utf8');

  // Generate embedded data JavaScript
  const embeddedData = `
        // ===== GENERATED DATA (from JSON files) =====
        // Do not edit this section - it's auto-generated by build.js

        const DUA_LIBRARY = ${JSON.stringify(duasWithDerived, null, 2)};
        const THEMES = ${JSON.stringify(data.themes, null, 2)};
        const ROUNDS = ${JSON.stringify(data.rounds, null, 2)};

        // ===== END GENERATED DATA =====
`;

  // Replace placeholder in template
  template = template.replace('/*DATA_PLACEHOLDER*/', embeddedData);

  // Write output
  fs.writeFileSync(outputPath, template, 'utf8');

  console.log('✅ Build successful!');
  console.log(`   Generated: ${outputPath}`);
  console.log(`   Size: ${(template.length / 1024).toFixed(2)} KB`);
  console.log(`   Duas: ${Object.keys(data.duas).length}`);
  console.log(`   Themes: ${Object.keys(data.themes).length}`);
}

main();
